members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'
urlpatterns = [
    url(r'^apply/$', views.new_member_application, name='apply'),
]

sny_public_website/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^jäsenedut$', views.perks, name='perks')
]

snyapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^members/', include('members.urls')),
    url(r'^', include('sny_public_website.urls')),
    url(r'^admin/', admin.site.urls),
]

members/models.py
from django.db import models

# from django.utils import timezone
# from django.core.validators import MaxValueValidator, MinValueValidator

class Member(models.Model):
    name = models.CharField(max_length=255)
    place_of_residence = models.CharField(max_length=255)
    email_addr = models.EmailField()
    joined = models.DateTimeField(auto_now_add=True)
    confirmed_member = models.BooleanField(default=False)

    def __str__(self):
        return self.name

# class Observation(models.Model):
#     title = models.CharField(max_length=255)
#     tags = TaggableManager(through=TaggedItem)
#     # timestamp = models.DateTimeField(default=timezone.now)
#     start_time = models.DateTimeField(default=timezone.now)
#     subject = models.CharField(max_length=255, default="Me")
#     annotation = models.CharField(max_length=2048)
#
#     def __str__(self):
#         return self.title
#
# class SpannedObservation(Observation):
#     # title = models.CharField(max_length=255)
#     # tags = TaggableManager(through=TaggedItem)
#     # start_time = models.DateTimeField(default=timezone.now)
#     end_time = models.DateTimeField()
#     # subject = models.CharField(max_length=255, default="Me")
#     # annotation = models.CharField(max_length=2048)
#     # def __str__(self):
#     #     return self.title
#
# class PsychoState(models.Model):
#     title = models.CharField(max_length=255)
#     timestamp = models.DateTimeField(default=timezone.now)
#     valence = models.FloatField(
#         validators=[MinValueValidator(-100), MaxValueValidator(100)]
#     )
#     arousal = models.FloatField(
#         validators=[MinValueValidator(0), MaxValueValidator(100)]
#     )
#     annotation = models.CharField(max_length=2048)
#
#     def __str__(self):
#         return ', '.join([self.title, str(self.valence), str(self.arousal)])

sny_public_website/models.py
from django.db import models

# Create your models here.

members/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Member

# Create your views here.
def new_member_application(request):
    payload = request.POST
    if not payload:
        return HttpResponse("Tarviin tiedot.")
    elif Member.objects.filter(email_addr=payload['email_addr']):
        return HttpResponse("S-pode jonkun muun (??) käytössä.")
    else:
        new_applicant = Member(
            name=payload['name'],
            place_of_residence=payload['place_of_residence'],
            email_addr=payload['email_addr'])
        new_applicant.save()

    return HttpResponse("Tallennettu.")

sny_public_website/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    # allevents = PsychoState.objects.all()
    # print([str(n) for n in allevents])
    # return HttpResponse("Hello everyone! We're at the root now.")
    return render(request, 'index.html')

def perks(request):
    raise RuntimeError("I don't know anything about that")

sny_public_website/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Suomen nykytaide ry</title>
    <style type="text/css">
        body {
            margin:40px auto;
            max-width:650px;
            line-height:1.6;
            font-size:18px;
            color:#444;
            padding:0 10px;
            background-color: #EEEEEE;
        }
        h1, h2, h3 {
            line-height:1.2;
        }
        img {
            max-width: 650px;
        }
    </style>
</head>
<body>
    <header>
        <img src='/static/abstract_01.png'>
        <h1>Suomen nykytaide ry</h1>
        <aside>Suomalaisen nykytaiteen ja audiovisuaalisen nykykulttuurin edistäjä.</aside>
    </header>
    <br><br>
    <hr>
    <h2>Nyt jos koskaan kannattaa ???</h2>
    <p><strong>Helposti faktana pidettävä asia.</strong></p>
    <p>Oletko koskaan miettinyt, ei tarvitse enää. Todistan nyt em. Asian todeksi näiden syiden takia:</p>
    <ul>
        <li>Kyllä</li>
        <li>Joo kyllä se näin joo sen juuri on oltava</li>
        <li>Joo joo joo joo</li>
        <li><em>Kyllä</em> se <em>on</em> kato</li>
        <li>Joo kyllä joo niin olikin</li>
    </ul>

    <h3>Ja aivan! Arvasit oikein:</h3>
    <p>Myös <em>Sinä</em> voit liittyä mukaan. Jäsenyyteen liittyy maksu, eivätkä jäsenet saa juuri mitään <a href="/jäsenedut">etuuksia</a>. Täytä allaoleva lomake niin rupeamme luultavasti lähettelemään sinulle sähköposteja.</p>

    <hr>
    <h3>Ja siitä</h3>
    <form action="{% url 'members:apply' %}" method="post">
        {% csrf_token %}
        <input placeholder="Täydellinen nimi" required type="text" name="name" id="name" maxlength="255" />
        <label for="name">Nimi</label>
        <br />
        <input placeholder="Kotipaikka" required type="text" name="place_of_residence" id="place_of_residence" maxlength="255" />
        <label for="name">Kotipaikka</label>
        <br />
        <input placeholder="Sähköposti" required type="email" name="email_addr" id="email_addr"/>
        <label for="name">Sähköposti</label>
        <br />
        <input type="submit" value="Lähetä" />
    </form>

    <hr>
    <p>Koodia copypastettu mm. <a href="http://bettermotherfuckingwebsite.com/">täältä</a> ja <a href="https://en.wikipedia.org/wiki/Missionary_Church_of_Kopimism">copymixauksen</a> tulokset on <a href="https://github.com/hkotkanen/snyapp">täällä</a>.